# Simplified deployment - just the Chronology Agent and Ollama
services:
  # Main Chronology Agent Application
  chronology-agent:
    build: .
    container_name: chronology-agent
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./uploads:/app/uploads
      - ./sample_documents:/app/sample_documents:ro
    depends_on:
      - ollama
    restart: unless-stopped

  # Ollama for Local AI Models
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
