[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/tags"
healthcheckTimeout = 300
restartPolicyType = "always"
replicas = 1

[env]
OLLAMA_HOST = "0.0.0.0"
OLLAMA_ORIGINS = "*"
